emg:
  databases:
    default:
      ENGINE: 'django.db.backends.mysql'
      NAME: 'emg'
      USER: 'root'
      # PASSWORD: 'secret'
      HOST: 127.0.0.1
      PORT: 3306
  session_engine: 'django.contrib.sessions.backends.cache'
  # caches:
  #   default:
  #     BACKEND: "django_redis.cache.RedisCache"
  #     LOCATION: "redis://127.0.0.1:6379/0"
  #     KEY_PREFIX: "emg"
  emg_backend_auth: "https://backend"
